/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Gd9xoquZHZA
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/components/ui/card"
import { Label } from "@/components/components/ui/label"
import { Input } from "@/components/components/ui/input"
import { Button } from "@/components/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/components/ui/table"
import { Badge } from "@/components/components/ui/badge"

export function Component() {
  return (
    <>
      <Card className="w-full max-w-2xl">
        <CardHeader>
          <CardTitle>Customer Profile</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter customer's name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter customer's email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="address">Address</Label>
            <Input id="address" placeholder="Enter customer's address" />
          </div>
        </CardContent>
        <CardFooter>
          <Button className="ml-auto">Save</Button>
        </CardFooter>
      </Card>
      <Card className="w-full mt-6">
        <CardHeader>
          <CardTitle>Customer Data</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Purchase ID</TableHead>
                <TableHead>Product</TableHead>
                <TableHead>Quantity</TableHead>
                <TableHead>Total Price</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>INV001</TableCell>
                <TableCell>Product A</TableCell>
                <TableCell>2</TableCell>
                <TableCell>$100.00</TableCell>
                <TableCell>12/12/2023</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>INV002</TableCell>
                <TableCell>Product B</TableCell>
                <TableCell>1</TableCell>
                <TableCell>$50.00</TableCell>
                <TableCell>12/12/2023</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      <Card className="w-full mt-6">
        <CardHeader>
          <CardTitle>Account Status</CardTitle>
        </CardHeader>
        <CardContent>
          <Badge className="text-green-500 bg-green-100">Active</Badge>
        </CardContent>
      </Card>
    </>
  )
}
